image: clever/drone-node:6.2.2
notify:
  email:
    recipients:
    - drone@clever.com
publish:
  catapult:
    url: $$catapult_url
    application: $$app_name
  docker:
    docker_host: $$docker_server
    email: $$docker_email
    image_name: clever/$$app_name
    password: $$docker_password
    registry_login: true
    tags:
    - $(git rev-parse --short HEAD)
    username: $$docker_username
    when:
      branch: master
script:
  - npm install
  - make test
  - make build
